# Overview of the Shiny Application

link_one <- tags$a(href = "https://www.smithsonianmag.com/smart-news/science-proves-pop-music-has-actually-gotten-worse-8173368/?fbclid=IwAR2fT9AvxD9vDZRDUuZonxwgWl-Sgg_8hr8fnbpNKxWSzM9u1a2SCVSACEM",
                   "Or at least that's what people think!")

intro <- p("Ever since Rock and Roll, American Music has been in a constant
     decline.", link_one, "We are going to rock
     and roll through the history of American Music, from 1950's to
     now to see exaclty how music has changed. Specifically, we will
     be looking at three questions. Our first question, How the length of albums
     have changed, will be looking at album lengths based on number of tracks
     and the duration of the album in minutes. Next, we look at how the Top
     500 albums' genres have shifted over the years. Finally, we will look at
     how music lyrics and their social messages have changed over time. We hope
     you learn a lot about the history of American Music!")

link_two <- tags$a(href = "https://www.kaggle.com/rakannimer/billboard-lyrics",
                   "this Kaggle dataset.")

link_three <- tags$a(href = "https://www.billboard.com/archive/charts",
                     "Billboard,")

set_one_info <- p("This dataset was originally found on ", link_two,
    "Its data was originally generated by ", link_three,
    "an American entertainment company, who collected the data by monitoring
    airplay at many stations in the United States.")

link_four <- tags$a(href = "https://www.kaggle.com/notgibs/500-greatest-albums-of-all-time-rolling-stone",
                    "a Kaggle dataset.")
link_five <- tags$a(href = "https://www.rollingstone.com/music/music-lists/500-greatest-albums-of-all-time-156826/",
                    "Rolling Stone Magazine,")
set_two_info <- p("This dataset was also found on ", link_four,
    "The music data was first generated by ", link_five,
    "who conducted an extensive review process in collecting the
    data. Rolling Stone is an American magazine that focuses on
    popular culture in regards to music, film, TV, and politics.")


link_six <- tags$a(href = "https://components.one/datasets/billboard-200/",
                   "this website called Components, ")
link_seven <- tags$a(href = "https://www.billboard.com/archive/charts",
                     "Billboard, ")
link_eight <- tags$a(href = "https://en.wikipedia.org/wiki/Billboard_magazine",
                     "wikipedia page.")
set_three_info <- p("This dataset was originally found on ", link_six,
    "which I discovered through a subReddit called R/datasets and looking up
    music. Its data was originally generated by ",
    link_seven, "using their Top 200 Albums list. It's important to note that
    the popularity of an album can be affected by single
    songs so it would also be interesting to see how the top
    albums match up with the top songs using dataset 1.")

overview <- tabPanel(
  "Overview",
  titlePanel("Overview of American Music"),
  intro,
  br(),
  tags$img(src = "rock.gif", width = "100px", height = "100px"),
  h3("Our Data Sets"),
  h4("Data Source 1 - Billboard 1964-2015 Songs + Lyrics"),
  set_one_info,
  h4("Data Source 2 - Rolling Stone's 500 Greatest Albums"),
  set_two_info,
  h4("Data Source 3 - Billboard 1963-2019 Top 200 Albums Per Week"),
  set_three_info
)
